blank_issues_enabled: false
contact_links:
  - name: Start a discussion (config, doubts, docs)
    url: https://github.com/jbergler/hass-ttlock/discussions
    about: If you have general questions, or are unsure about whether a bug report is the right thing to open, click here to create a Discussion instead of an Issue.
