configure_passage_mode:
  name: Configure passage mode
  description: Tries to configure passage mode for a lock (or set of locks)
  target:
    entity:
      integration: ttlock
      domain: lock
  fields:
    enabled:
      name: Enabled
      description: Should passage mode be active (if false, no other fields are required)
      required: true
      default: true
      selector:
        boolean:
    auto_unlock:
      name: Auto-unlock
      description: Should the the lock auto unlock when passage mode starts
      required: false
      default: false
      selector:
        boolean:
    all_day:
      name: All day
      description: If set, the enabled setting applies 24/7. If not set then start_time, end_time and week_days is required.
      required: false
      default: false
      selector:
        boolean:
    start_time:
      name: Start time
      description: When passage mode should begin (only hour + minute, seconds are ignored)
      required: false
      default: "00:00"
      selector:
        time:
    end_time:
      name: End time
      description: When passage mode should end (only hour + minute, seconds are ignored)
      required: false
      default: "00:00"
      selector:
        time:
    days:
      name: Week days
      description: Which days should the passage mode schedule apply to?
      required: false
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun
          multiple: true
          mode: list
